### ISSUE TITLE
keep column position please

### ISSUE THREAD

**Issue by jk2K** [hidu/mysql-schema-sync#1]
source
![image](https://cloud.githubusercontent.com/assets/4025839/16798783/489f5f44-4920-11e6-809c-ba973910e051.png)

destination
![image](https://cloud.githubusercontent.com/assets/4025839/16798922/ec504180-4920-11e6-90b8-a348892953da.png)
`zodiac_sign` not behind `birthday`

keep column position please, thanks

**Comment by hidu** [comment]
next version's features,but now there is no schedule.
thanks
