### ISSUE TITLE
表同步出现错误,想问一下最低支持的mysql版本

### ISSUE THREAD

**Issue by dexvo** [hidu/mysql-schema-sync#2]
EXEC_SQL_FAIELD Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ';
ALTER TABLE `n_system_apply`
ADD CONSTRAINT `FK_10egw3bdhwrghm091ueehk8te` FOR' at line 3
<img width="1381" alt="c9ebe276095a131821bdb5c44a534ec9" src="https://cloud.githubusercontent.com/assets/7923085/20254360/ba4d1ad2-aa6e-11e6-9298-db666184c0d6.png">

**Comment by hidu** [comment]
mysql 5以上
外键约束条件是否有 “On XXX”条件，比如  On delete  或者 on update ?

**Comment by dexvo** [comment]
on delete 和 on update 均为restrict, 是不是有这个约束就不能正确建立外键。这种情况该怎么解决,有没有好的解决办法。

**Comment by hidu** [comment]
MultiQueries 的问题，加了个兼容重试的策略，可以再试试。

**Comment by dexvo** [comment]
问题依旧存在，而且这个会导致一部分表不能成功更新。
<img width="1243" alt="2fd37e74356ac2cd91691ec27571e426" src="https://cloud.githubusercontent.com/assets/7923085/20740599/4970cfb4-b6ff-11e6-9ab6-d3669af4a8cd.png">

**Comment by hidu** [comment]
看日志，你的程序还没有更新。更新一下试试：
```
go get -u github.com/hidu/mysql-schema-sync
```

**Comment by dexvo** [comment]
谢谢解答，我试了一下已经可以了。
