### ISSUE TITLE
支持SSH隧道

### ISSUE THREAD

**Issue by iineva** [hidu/mysql-schema-sync#22]
数据库在防火墙后面，需要通过SSH隧道进行连接，希望能添加此功能

**Comment by hidu** [comment]
具体场景是怎样的？先ssh 登陆，然后才能连接mysql？

**Comment by iineva** [comment]
实际生产环境中，数据库网络一般不会暴露在公网中。
ssh可以做端口映射，可以通过公网的ssh端口连接，把后端服务器的某个ip上的端口映射到本地，这样通过访问本地端口就能访问到服务器后端的数据库了。
很多数据库工具都提供了这个功能，数据库GUI工具Navicat就提供了这个功能。
开源的工具有medis，做的是redis的GUI工具，也提供了一样的功能，可以参考其实现。

**Comment by mercykevin** [comment]
那直接用ssh把数据库的端口映射到本地不就行了吗

**Comment by iineva** [comment]
> 那直接用ssh把数据库的端口映射到本地不就行了吗

这样做当然可以，但是我提出这个issues是为了让这个工具更好用

**Comment by hidu** [comment]
不属于这个工具考虑的
