### ISSUE TITLE
在楼主的功能的基础上,加了一个数据同步的功能

### ISSUE THREAD

**Issue by weichangdong** [hidu/mysql-schema-sync#26]
有需要的,我可以放到github上

**Comment by weichangdong** [comment]
比较粗糙,自己同步测试环境和本地环境的数据~

**Comment by hidu** [comment]
同步数据最好是单独开，这个就专门同步schema do hi 邮箱：duv123@gmail.com 签名由 网易邮箱大师 定制 在2019年05月29日 10:35，东哥 写道： Closed #26. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
