### ISSUE TITLE
不能用，skip

### ISSUE THREAD

**Issue by xxlxiangxiaolin** [hidu/mysql-schema-sync#28]
2019/06/13 db.go:85: [SQL] [source] show table status []
2019/06/13 schemaSync.go:265: source db table total: 1
2019/06/13 schemaSync.go:270: Index : 0 Table : test
2019/06/13 schemaSync.go:277: Table: test skip
2019/06/13 schemaSync.go:303: trace changedTables: map[]
2019/06/13 schemaSync.go:352: execute_all_sql_done,success_total: 0 failed_total: 0
2019/06/13 statics.go:137: no table change,skip send mail

{
     "source":"root:root@(192.168.1.189:3306)/test",
     "dest":"root:root@(192.168.1.189:3306)/test2",
"tables":[],
     "email":{
          "send_mail":true,
         "smtp_host":"*****",
         "from":"*****",
         "password":"*****",
         "to":"*****"
     }
}

**Comment by 514366607** [comment]
我改错东西了。没有合并到master，config.json tables_ignore  随便加个表名上去，暂时这样可以解决

**Comment by nwpull** [comment]
加上也不行吧

**Comment by xxlxiangxiaolin** [comment]
对的，我没用




------------------ 原始邮件 ------------------
发件人: "nwpull"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 下午2:19
收件人: "hidu/mysql-schema-sync"<mysql-schema-sync@noreply.github.com>;
抄送: "相晓林"<xxiangxiaolin@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hidu/mysql-schema-sync] 不能用，skip (#28)




加上也不行吧

**Comment by nwpull** [comment]
那有用什么取代方案了吗？

**Comment by xxlxiangxiaolin** [comment]
jenkins里处理了



------------------ 原始邮件 ------------------
发件人: "nwpull"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 下午2:22
收件人: "hidu/mysql-schema-sync"<mysql-schema-sync@noreply.github.com>;
抄送: "相晓林"<xxiangxiaolin@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hidu/mysql-schema-sync] 不能用，skip (#28)




那有用什么取代方案了吗？

**Comment by nwpull** [comment]
写脚本吗，备份还是同步？

**Comment by xxlxiangxiaolin** [comment]
差不多就是脚本运行sql




------------------ 原始邮件 ------------------
发件人: "nwpull"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 下午2:25
收件人: "hidu/mysql-schema-sync"<mysql-schema-sync@noreply.github.com>;
抄送: "相晓林"<xxiangxiaolin@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hidu/mysql-schema-sync] 不能用，skip (#28)




写脚本吗，备份还是同步？

**Comment by nwpull** [comment]
嗯嗯，好的，谢谢思路

**Comment by robert1070** [comment]
这个项目死掉了？我遇到的问题和一楼一样，全是skip

**Comment by robert1070** [comment]
拉了二楼fork的代码，可以跑通，需要改import包的问题

**Comment by Rmond** [comment]
> 我改错东西了。没有合并到master，config.json tables_ignore 随便加个表名上去，暂时这样可以解决

这样也不行，还是skip

**Comment by hidu** [comment]
fixd
