### ISSUE TITLE
能否在一个json里，搞定多个库(相同用户、主机)？而不用写多个json？

### ISSUE THREAD

**Issue by xiaopengshi** [hidu/mysql-schema-sync#35]
也就是说，在json里只需指定默认库名，而执行时，去扫描所有库下的所有表

**Comment by hidu** [comment]
配置会更复杂，不太好管理，暂不支持

**Comment by xiaopengshi** [comment]
我的分支上已支持，空了帮忙rwview下发自我的华为手机-------- 原始邮件 --------发件人： do it <notifications@github.com>日期： 2020年4月25日周六 早上7:11收件人： hidu/mysql-schema-sync <mysql-schema-sync@noreply.github.com>抄送： "shixiaopeng.rc" <sxp_fine@163.com>, Author <author@noreply.github.com>主    题： Re: [hidu/mysql-schema-sync] 能否在一个json里，搞定多个库(相同用户、主机)？而不用写多个json？ (#35)

配置会更复杂，不太好管理，暂不支持
