### ISSUE TITLE
config.json中密码有特殊字符‘@’，请教怎么转义啊

### ISSUE THREAD

**Issue by Noooodles** [hidu/mysql-schema-sync#54]
求教数据库用户的密码包含了特殊字符的情况怎么转义？

**Comment by hidu** [comment]
看底层依赖的 driver ，应该是不支持这个特殊字符的

**Comment by loveyu** [comment]
https://github.com/go-sql-driver/mysql/issues/897

官方无意解决似乎

**Comment by loveyu** [comment]
https://github.com/go-sql-driver/mysql/issues/421

实际是支持的，不需要对这个字符串进行转义

倒序查找，从最后一个@开始查找
https://github.com/go-sql-driver/mysql/blob/master/dsn.go#L306

**Comment by Noooodles** [comment]
> [go-sql-driver/mysql#421](https://github.com/go-sql-driver/mysql/issues/421)
> 
> 实际是支持的，不需要对这个字符串进行转义
> 
> 倒序查找，从最后一个@开始查找 https://github.com/go-sql-driver/mysql/blob/master/dsn.go#L306

我后来确实验证过，不需要转义，直接可用。

**Comment by 514366607** [comment]
你升级下go的版本就行。太老的版本不支持。

**Comment by hidu** [comment]
支持
比如 password:  `tes!@x@test`
```
     "dest":"tmp22:tes!@x@test@(127.0.0.1:3306)/test_1",
```
