### ISSUE TITLE
如何能不删除目的数据库中多出来的表

### ISSUE THREAD

**Issue by Urnotprepared** [hidu/mysql-schema-sync#56]
如何能不删除目的数据库中多出来的表
比如：目的DB 比  源DB 多出来一个表t1
在执行：mysql-schema-sync -conf mydb_conf.json 2>/dev/null >db_alter.sql
文件 db_alter.sql 中会有一个 drop table t1 的语句
咱们项目的 readme 中提到 “默认情况不会对多出的表、字段、索引、外键删除”
但还是会执行 drop 操作，这里是不是存在BUG ？

**Comment by hidu** [comment]
多出来的表是应该不删除才对，实现是有问题

**Comment by Urnotprepared** [comment]
请问什么时候能 fix，感谢回复

**Comment by hidu** [comment]
试试最新版本的

**Comment by Urnotprepared** [comment]
应该没问题了
