### ISSUE TITLE
能否去掉建表语句中的 AUTO_INCREMENT= XXX

### ISSUE THREAD

**Issue by Urnotprepared** [hidu/mysql-schema-sync#57]
能否去掉建表语句中的 AUTO_INCREMENT= XXX
希望在目的端建新表的时候， AUTO_INCREMENT= 1 或者把 AUTO_INCREMENT= XXX 去掉

**Comment by hidu** [comment]
去掉后，写入的时候不带 pk 是会报错的啊，这是出于什么目的？

**Comment by Urnotprepared** [comment]
可能是我没表达清楚
比如：
CREATE TABLE `t1` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(100) NOT NULL,
    PRIMARY KEY (`id`)
  ) ENGINE=InnoDB AUTO_INCREMENT=1065290 DEFAULT CHARSET=utf8mb4;
  
  
把 AUTO_INCREMENT=1065290 去掉 或者替换为 AUTO_INCREMENT=1

变成：
CREATE TABLE `t1` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(100) NOT NULL,
    PRIMARY KEY (`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

**Comment by hidu** [comment]
ok 明白，就是创建新表的时候，重置 AUTO_INCREMENT 的值。
需求和功能合理，欢迎提交 pr。

**Comment by Urnotprepared** [comment]
感谢回复~

**Comment by Urnotprepared** [comment]
20220311.2 , 使用这个版本，好像没有去掉

**Comment by hidu** [comment]
我测试是已经去掉了，把新表的 schema 的最后一行贴一下？

**Comment by Urnotprepared** [comment]
ENGINE=InnoDB AUTO_INCREMENT=4049116 DEFAULT CHARSET=utf8mb4;
