### ISSUE TITLE
无法通过go install 安装

### ISSUE THREAD

**Issue by Joker-batman** [hidu/mysql-schema-sync#58]
因为我的网络原因 无法通过go install 进行安装
我是否能将master.zip 下载下来进行编译呢？

**Comment by hidu** [comment]
可以自己编译



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月11日 14:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [hidu/mysql-schema-sync] 无法通过go install 安装 (Issue #58) |

因为我的网络原因 无法通过go install 进行安装
我是否能将master.zip 下载下来进行编译呢？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
