### ISSUE TITLE
dest 支持填多个吗?

### ISSUE THREAD

**Issue by Subfire** [hidu/mysql-schema-sync#77]

**Comment by hidu** [comment]
不支持



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月12日 18:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [hidu/mysql-schema-sync] dest 支持填多个吗? (Issue #77) |
